//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Itemtransactions = new HashSet<Itemtransaction>();
        }
    
        public int itemkey { get; set; }
        public string RFIDkey { get; set; }
        public string name { get; set; }
        public string object_description { get; set; }
        public Nullable<int> itemgroupkey { get; set; }
        public Nullable<int> photokey { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<System.DateTime> delete_date { get; set; }
    
        public virtual Itemgroup Itemgroup { get; set; }
        public virtual Photo Photo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Itemtransaction> Itemtransactions { get; set; }
    }
}
