//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StashEntities : DbContext
    {
        public StashEntities()
            : base("name=StashEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Box> Boxes { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Itemgroup> Itemgroups { get; set; }
        public virtual DbSet<Itemtransaction> Itemtransactions { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
    }
}
